main: serversystem.main.ServerSystem
name: ServerSystem
version: "1.9"
author: Der_Zauberer
api-version: 1.12

commands:
  admin:
    description: Open the admin menu
    usage: /<command>
    permission: serversystem.command.admin
  back:
    description: Teleports the player to his last teleporting position
    usage: /<command>
    permission: serversystem.command.back
  build:
    description: Allow the player to build in protected worlds
    usage: /<command> [<player>]
    permission: serversystem.command.build
  enderchest:
    description: Open the enderchest of a player
    usage: /<command> [<player>]
    permission: serversystem.command.enderchest
  fly:
    description: Allow the player to fly
    usage: /<command>
    permission: serversystem.command.fly
  inventory:
    description: Open the inventory of a player
    usage: /<command> [<player>]
    permission: serversystem.command.inventory
  lobby:
    description: Teleport player to lobby
    usage: /<command>
    permission: serversystem.command.lobby
  permission:
    description: Set the permissions of a player
    usage: /<command> [<player>] [<group>]
  ping:
    description: Returns the connection delay between server and client
    usage: /<command>
    permission: serversystem.command.ping
  speed:
    description: Toggle players speed
    usage: /<command>
    permission: serversystem.command.speed
  vanish:
    description: Allow the player to vanish
    usage: /<command> [<player>]
    permission: serversystem.command.vanish
  warp:
    description: Teleport player to a location
    usage: /<command> <warp>] [<action>] [<option>] [value]
    permission: serversystem.command.warp
  world:
    description: Teleport player to an other world or edit an other world
    usage: /<command> [<world>] [<action>] [<option>] [value]
    permission: serversystem.command.world
  wtp:
    description: Teleoprt player to an other world
    usage: /<command> [<word>]
    permission: serversystem.command.world
  
permissions:
  serversystem.command.admin:
    description: Open the admin inventory
    default: op
  serversystem.command.back:
    description: Teleports the player to his last teleporting position
    default: op
  serversystem.command.build:
    description: Allow the player to build in protected worlds
    default: op
  serversystem.command.enderchest:
    desciption: Open the enderchest of a player
    default: op
  serversystem.command.fly:
    desciption: Allow the player to fly
    default: op
  serversystem.command.inventory:
    desciption: Open the inventory of a player
    default: op
  serversystem.command.lobby:
    description: Teleport player to lobby
    default: true
  serversystem.command.permission:
    description: Set the permissions of a player
    default: false
  serversystem.command.ping:
    description: Returns the connection delay between server and client
    default: true
  serversystem.command.speed:
    description: Toggle players speed
    default: op
  serversystem.command.vanish:
    description: Allow the player to vanish
    default: op
  serversystem.command.warp:
    description: Teleport player to a warp
    default: true
  serversystem.command.warp.edit:
    description: Edit a warp with the warp command
    default: op
  serversystem.command.world:
    description: Teleport player to an other world
    default: op
  serversystem.command.world.edit:
    description: Edit a world with the world command
    default: op
  serversystem.tools.adminstar:
    description: Open the admin inventory
    default: op
  serversystem.tools.commandblock:
    description: Allow to use commandblocks
    default: false
  serversystem.tools.disabledblocks:
    description: Allow to use in the config disabled blocks
    default: op
  serversystem.tools.signeddit:
    description: Allow to create executable signs
    default: op